server:
  port: 9095
  ssl:
    key-store: ${KEYSTORE_PATH}
    key-store-password: ${KEYSTORE_PASSWORD}
    keyStoreType: ${KEYSTORE_TYPE}
    keyAlias: ${KEYSTORE_ALIAS}
    enabled: true
    trust-store: ${TRUSTSTORE_PATH}
    trust-store-password: ${TRUSTSTORE_PASSWORD}
    trust-store-type: ${TRUSTSTORE_TYPE}
  servlet:
    context-path: /
spring:
  #上传大小设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
      resolve-lazily: false
cas:
  server-url-prefix: https://cas1.com:8443/cas
  server-login-url: https://cas1.com:8443/cas/login
  client-host-url: https://localhost:9095/
  validation-type: cas3